### ISSUE TITLE
Issue when generating a phylum legend with phyla not listed in phy_fun()

### ISSUE THREAD

**Issue by SteinAcker1** [CharlieCarpenter/tidyMicro#2]
Hello Charlie,

Thanks for creating this package! I've enjoyed using it so far. However, I've noticed an issue when creating Rocky Mountain plots. Whenever I include bacteria from phyla not included in the "phy" vector in the phy_fun() function, all taxonomical information is included in the legend, rather than just the phyla. I have attached an example from a family-level analysis.

Best wishes,
Stein

<img width="459" alt="bad_phyla" src="https://user-images.githubusercontent.com/67439517/114944966-d008be80-9e48-11eb-9d22-01160e7e3f3d.png">

**Comment by CharlieCarpenter** [comment]
Hi Stein,

Thank you for using the package! And thank you for bringing this to my attention. I will add the two Phylum in my next update cycle along with other updates.

Just out of curiosity, do you know where the NA/NA/NA/NA is coming from? Is that another issue or is that from your OTU table?

Thanks again,

Charlie

**Comment by SteinAcker1** [comment]
Hi Charlie,

Thanks for your reply! I looked through my input OTU tables, and it appears that the NA's are from my own input rather than from the tidyMicro package. They're nothing you need to worry about.

Best wishes,
Stein

**Comment by CharlieCarpenter** [comment]
Hi Stein,

I added those two phylum to the phu_fun() list and pushed them to Github. You should be able to reinstall directly from Github now. 

Thanks!

Charlie
